services:
  lu_estilo_database:
    image: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u app_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  lu_estilo_backend:
    image: lu-estilo-api
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - lu_estilo_database
    env_file:
      - .env

volumes:
  pgdata:
